import { InterestListTypes } from "./definitions";

export const interestList: InterestListTypes[] = [
  {
    id: 1,
    name: "Shoes",
    checked: true,
  },
  {
    id: 2,
    name: "Men T-Shirts",
    checked: true,
  },
  {
    id: 3,
    name: "Makeup",
    checked: false,
  },
];

export const usersList: any = [
  {
    id: 1,
    name: "Guest User",
    email: "guest@user.com",
    password: "guestUser123",
  },
  {
    id: 2,
    name: "John Doe",
    username: "john@doe.in",
    password: "johnDoe123",
  },
];
export const categories = [
  { id: 1, categoryName: "Shoes", interested: true },
  { id: 2, categoryName: "T shirts", interested: false },
  { id: 3, categoryName: "Sarees", interested: true },
  { id: 4, categoryName: "Kurtas", interested: false },
  { id: 5, categoryName: "Traditionals", interested: true },
  { id: 6, categoryName: "Mobile", interested: false },
  { id: 7, categoryName: "Laptops", interested: true },
  { id: 8, categoryName: "Watches", interested: false },
  { id: 9, categoryName: "Headphones", interested: true },
  { id: 10, categoryName: "Backpacks", interested: false },
  { id: 11, categoryName: "Cameras", interested: true },
  { id: 12, categoryName: "Perfumes", interested: false },
  { id: 13, categoryName: "Jewelry", interested: true },
  { id: 14, categoryName: "Sunglasses", interested: false },
  { id: 15, categoryName: "Cosmetics", interested: true },
  { id: 16, categoryName: "Handbags", interested: false },
  { id: 17, categoryName: "Books", interested: true },
  { id: 18, categoryName: "Music", interested: false },
  { id: 19, categoryName: "Movies", interested: true },
  { id: 20, categoryName: "Gaming", interested: false },
  { id: 21, categoryName: "Fitness", interested: true },
  { id: 22, categoryName: "Home Decor", interested: false },
  { id: 23, categoryName: "Kitchen Appliances", interested: true },
  { id: 24, categoryName: "Furniture", interested: false },
  { id: 25, categoryName: "Gardening", interested: true },
  { id: 26, categoryName: "Tools", interested: false },
  { id: 27, categoryName: "Art Supplies", interested: true },
  { id: 28, categoryName: "Crafts", interested: false },
  { id: 29, categoryName: "Party Supplies", interested: true },
  { id: 30, categoryName: "Stationery", interested: false },
  { id: 31, categoryName: "Pet Supplies", interested: true },
  { id: 32, categoryName: "Baby Products", interested: false },
  { id: 33, categoryName: "Toys", interested: true },
  { id: 34, categoryName: "Sporting Goods", interested: false },
  { id: 35, categoryName: "Outdoor Equipment", interested: true },
  { id: 36, categoryName: "Travel Accessories", interested: false },
  { id: 37, categoryName: "Fitness Equipment", interested: true },
  { id: 38, categoryName: "Cycling Gear", interested: false },
  { id: 39, categoryName: "Swimwear", interested: true },
  { id: 40, categoryName: "Luggage", interested: false },
  { id: 41, categoryName: "Electronics", interested: true },
  { id: 42, categoryName: "Home Appliances", interested: false },
  { id: 43, categoryName: "Smart Home Devices", interested: true },
  { id: 44, categoryName: "Computers", interested: false },
  { id: 45, categoryName: "Tablets", interested: true },
  { id: 46, categoryName: "Printers", interested: false },
  { id: 47, categoryName: "Monitors", interested: true },
  { id: 48, categoryName: "Networking", interested: false },
  { id: 49, categoryName: "Software", interested: true },
  { id: 50, categoryName: "Office Supplies", interested: false },
  { id: 51, categoryName: "Fishing Gear", interested: true },
  { id: 52, categoryName: "Camping Gear", interested: false },
  { id: 53, categoryName: "Hiking Gear", interested: true },
  { id: 54, categoryName: "Outdoor Clothing", interested: false },
  { id: 55, categoryName: "Climbing Gear", interested: true },
  { id: 56, categoryName: "Water Sports Equipment", interested: false },
  { id: 57, categoryName: "Snow Sports Equipment", interested: true },
  { id: 58, categoryName: "Golf Equipment", interested: false },
  { id: 59, categoryName: "Team Sports Equipment", interested: true },
  { id: 60, categoryName: "Exercise Machines", interested: false },
  { id: 61, categoryName: "Yoga Accessories", interested: true },
  { id: 62, categoryName: "Boxing Gear", interested: false },
  { id: 63, categoryName: "Martial Arts Equipment", interested: true },
  { id: 64, categoryName: "Tennis Equipment", interested: false },
  { id: 65, categoryName: "Soccer Equipment", interested: true },
  { id: 66, categoryName: "Basketball Equipment", interested: false },
  { id: 67, categoryName: "Baseball Equipment", interested: true },
  { id: 68, categoryName: "Softball Equipment", interested: false },
  { id: 69, categoryName: "Gymnastics Equipment", interested: true },
  { id: 70, categoryName: "Volleyball Equipment", interested: false },
  { id: 71, categoryName: "Rugby Equipment", interested: true },
  { id: 72, categoryName: "Cricket Equipment", interested: false },
  { id: 73, categoryName: "Hockey Equipment", interested: true },
  { id: 74, categoryName: "Skateboarding Gear", interested: false },
  { id: 75, categoryName: "Surfing Gear", interested: true },
  { id: 76, categoryName: "Snowboarding Gear", interested: false },
  { id: 77, categoryName: "Skiing Gear", interested: true },
  { id: 78, categoryName: "Inline Skating Gear", interested: false },
  { id: 79, categoryName: "Motorcycle Gear", interested: true },
  { id: 80, categoryName: "Cycling Gear", interested: false },
  { id: 81, categoryName: "Car Accessories", interested: true },
  { id: 82, categoryName: "Truck Accessories", interested: false },
  { id: 83, categoryName: "SUV Accessories", interested: true },
  { id: 84, categoryName: "RV Accessories", interested: false },
  { id: 85, categoryName: "Motorcycle Accessories", interested: true },
  { id: 86, categoryName: "Boating Accessories", interested: false },
  { id: 87, categoryName: "ATV Accessories", interested: true },
  { id: 88, categoryName: "UTV Accessories", interested: false },
  { id: 89, categoryName: "Snowmobile Accessories", interested: true },
  { id: 90, categoryName: "Jet Ski Accessories", interested: false },
  { id: 91, categoryName: "Golf Cart Accessories", interested: true },
  { id: 92, categoryName: "Bicycle Accessories", interested: false },
  { id: 93, categoryName: "Water Sports Accessories", interested: true },
  { id: 94, categoryName: "Snow Sports Accessories", interested: false },
  { id: 95, categoryName: "Camping Accessories", interested: true },
  { id: 96, categoryName: "Hiking Accessories", interested: false },
  { id: 97, categoryName: "Outdoor Accessories", interested: true },
  { id: 98, categoryName: "Exercise Accessories", interested: false },
  { id: 99, categoryName: "Yoga Accessories", interested: true },
  { id: 100, categoryName: "Fitness Accessories", interested: false },
];


