"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "./reactQueryProvider";
import { DataProvider } from "./context";
import { useAuth } from "./lib/useAuth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 useAuth()
  return (
    <html lang="en">
      <ReactQueryProvider>
        <DataProvider>
          <body className={inter.className}>{children}</body>
        </DataProvider>
      </ReactQueryProvider>
    </html>
  );
}
